export * from './ping.controller';
export * from './storage.controller';
export * from './product.controller';
export * from './storage-inputoutput.controller';
export * from './product-inputoutput.controller';
export * from './inputoutput.controller';
export * from './storage-productstorage.controller';
export * from './product-productstorage.controller';
export * from './productstorage.controller';
